### PR TITLE
Provide github actions CI for #50

### PR DESCRIPTION
**Pull request by de-jcup**
- This adds a GitHub action workflow which automatically builds master branch as described at #50

### CODE REVIEW

**Comment by de-jcup** [comment]
Remark: Maybe it would be worth to fix some tests before doing the merge ? See https://github.com/de-jcup/winfoom/actions?query=workflow%3A%22Java+CI+with+Maven%22 for the current situation

**Comment by ecovaci** [comment]
The tests are OK. Problem is, there are some tests that generate some files and the CI server does not allow it.

**Comment by de-jcup** [comment]
@ecovaci

> here are some tests that generate some files and the CI server does not allow it.

I have used GitHub actions a lot now and I am generating documentation, test output etc. etc. and have absolutely no problems. So I cannot understand why it should not work.

By the way I tried to execute `.mvnw clean package` at a Windows machine and also at my Linux machine. On both machines I had test failures preventing the packaging build to be done. This is a little bit disturbing - I wanted to build my own release. If you would have a build CI which does work you are always in the situation that other developer could not complain about "It does not work on my machine" - like I do currently...

**Comment by ecovaci** [comment]
Here is the result of running the test on my computer:

[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 106, Failures: 0, Errors: 0, Skipped: 0

If you have test problems, just skip the tests.

**Comment by de-jcup** [comment]
My current build setup:

Windows 10 machine
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)

Output :` [ERROR] Tests run: 77, Failures: 6, Errors: 2, Skipped: 0`

Yes - I could just skip tests... but IMHO tests should work out-of-the-box and be green (at least for tags for releases).
So I think it would be much more better when change pushed on remote github repository would automatically inform maintainers 
about build problems.

Maybe you could just start a VM (e.g. with a standard Ubuntu) and do a simple build  there - so you would avoid a "works on my machine" situation.

**Comment by ecovaci** [comment]
Like I said, this application is not suitable for CI because the tests requires the right to create some files in the current user's home directory (like `/home/<current_user>/.winfoom/system.properties`) and the operating system must be Windows. Building Winfoom on platforms other than Windows makes no sense since Winfoom was initially designed for Windows and some tests can only be run on Windows.

**Comment by ecovaci** [comment]
The CI integration is possible starting with v3.3.0

**Comment by de-jcup** [comment]
At the GitHub actions workflow page you can create status badge markdown . Maybe you could add to your README.md ?

**Comment by ecovaci** [comment]
Done!

**Pull request merged**
